agents:
  queue: "k8s-builders"

steps:
  - label: Terraform Apply and Destroy Private
    key: apply-destroy-private
    command: .buildkite/scripts/apply.sh --TF_DIR examples/private --PREFIX rp-private --AWS_ACCESS_KEY_ID $DA_AWS_ACCESS_KEY_ID --AWS_SECRET_ACCESS_KEY $DA_AWS_SECRET_ACCESS_KEY
    plugins:
      - docker#v5.4.0:
          image: glrp/atgt:latest
          environment:
            - DA_AWS_ACCESS_KEY_ID
            - DA_AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION
